export const fields = [
  {
    id: 'firstName',
    type: 'text',
    isFull: true,
    placeholder: 'First Name',
    required: true,
    optionKey: '',
    disabled: false,
    halved: true,
  },
  {
    id: 'lastName',
    type: 'text',
    isFull: true,
    placeholder: 'Last Name',
    required: true,
    options: [],
    disabled: false,
    halved: true,
  },
  {
    id: 'phoneNumber',
    type: 'text',
    label: '',
    placeholder: 'Phone number',
    required: false,
    halved: true,
  },
  {
    id: 'email',
    type: 'email',
    isFull: false,
    placeholder: 'Email',
    required: true,
    options: [],
    disabled: false,
    halved: true,
  },
  {
    id: 'password',
    type: 'password',
    isFull: false,
    placeholder: 'Password',
    required: true,
    options: [],
    disabled: false,
    halved: true,
  },
  {
    id: 'confirmPassword',
    type: 'password',
    isFull: false,
    placeholder: 'Confirm Password',
    required: true,
    options: [],
    disabled: false,
    halved: true,
  },
];
